apiVersion: v1
kind: Secret
metadata:
  name: mariadb-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harvest-consultations.labels" . | nindent 4 }}
type: Opaque
data:
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | b64enc | quote }}
  MARIADB_USER: {{ .Values.mariadb.user | b64enc | quote }}
  MARIADB_PASSWORD: {{ .Values.mariadb.password | b64enc | quote }}
