apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harvest-consultations.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  MARIADB_ROOT_PASSWORD: {{ .Values.mariadb.rootPassword | b64enc | quote }}
  {{- end }}
  DB_USER: {{ .Values.db.user | b64enc | quote }}
  DB_PASSWORD: {{ .Values.db.password | b64enc | quote }}
