{{- if not .Values.db.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "harvest-consultations.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mariadb.enabled }}
  {{ .Values.db.secretKeys.rootPassword }}: {{ .Values.mariadb.rootPassword | b64enc | quote }}
  {{- end }}
  {{ .Values.db.secretKeys.user }}: {{ .Values.db.user | b64enc | quote }}
  {{ .Values.db.secretKeys.password }}: {{ .Values.db.password | b64enc | quote }}
{{- end }}
