harvestConsultations:
  failedJobsHistoryLimit: 3
  harvest:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
    image:
      repository: ghcr.io/wagov-dtt/harvest-consultations
      tag: 0.4.1
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: "1"
        memory: 1Gi
      requests:
        cpu: 100m
        memory: 256Mi
  nodeSelector: {}
  podSecurityContext:
    fsGroup: 10001
    runAsGroup: 10001
    runAsNonRoot: true
    runAsUser: 10001
    seccompProfile:
      type: RuntimeDefault
  schedule: 0 18 * * *
  startingDeadlineSeconds: 3600
  successfulJobsHistoryLimit: 3
  tolerations: []
  topologySpreadConstraints: []
kubernetesClusterDomain: cluster.local
