- op: add
  path: /spec/jobTemplate/spec/template/spec/containers/0/env
  value:
    - name: MYSQL_HOST
      value: mariadb
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          name: mariadb-credentials
          key: MARIADB_USER
    - name: MYSQL_PWD
      valueFrom:
        secretKeyRef:
          name: mariadb-credentials
          key: MARIADB_PASSWORD
    - name: MYSQL_DATABASE
      value: harvest
