apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: harvest-consultations

configMapGenerator:
  - name: harvest-config
    files:
      - harvest.sql

secretGenerator:
  - name: mariadb-credentials
    literals:
      - MARIADB_ROOT_PASSWORD=harvest
      - MARIADB_USER=harvest
      - MARIADB_PASSWORD=harvest

resources:
  - namespace.yaml
  - mariadb-service.yaml
  - mariadb-statefulset.yaml
  - harvest-cronjob.yaml

patches:
  - target:
      group: batch
      version: v1
      kind: CronJob
      name: harvest-cronjob
    path: harvest-cronjob-patch.yaml
