apiVersion: batch/v1
kind: CronJob
metadata:
  name: harvest-cronjob
spec:
  schedule: "@hourly"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: harvest
              image: ghcr.io/wagov-dtt/harvest-consultations:dev
              imagePullPolicy: IfNotPresent
              command: ["sqlmesh", "plan", "--auto-apply", "--run", "--verbose"]
              volumeMounts:
                - mountPath: /app/logs
                  name: ephemeral
                  subPath: logs
                - mountPath: /app/.cache
                  name: ephemeral
                  subPath: cache
                - mountPath: /home/appuser/.sqlmesh
                  name: ephemeral
                  subPath: appuser.sqlmesh
                - mountPath: /home/appuser/.duckdb
                  name: ephemeral
                  subPath: appuser.duckdb
              envFrom:
                - secretRef:
                    name: harvest-secret
              securityContext:
                runAsNonRoot: true
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
          restartPolicy: Never
          volumes:
            - name: ephemeral
              emptyDir: {}

