apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: percona-mysql
spec:
  serviceName: mysqldb
  selector:
    matchLabels:
      app: percona-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: percona-mysql
    spec:
      containers:
        - name: percona-mysql
          image: percona/percona-server:8.4
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef: { name: harvest-secret, key: MYSQL_PWD }
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  { name: harvest-secret, key: SQLMESH__VARIABLES__OUTPUT_DB }
